# Generated by Django 4.2.26 on 2025-11-25 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(max_length=32, unique=True, verbose_name='文件唯一标识(MD5)')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('total_chunks', models.PositiveIntegerField(verbose_name='总分片数')),
                ('uploaded_chunks', models.JSONField(default=list, verbose_name='已上传的分片索引列表')),
                ('status', models.CharField(choices=[('pending', '上传中'), ('completed', '已完成'), ('failed', '上传失败')], default='pending', max_length=20, verbose_name='上传状态')),
                ('subject', models.CharField(default='未分类', max_length=50, verbose_name='学科')),
                ('grade', models.CharField(default='未指定', max_length=20, verbose_name='年级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tasks', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '分片上传任务',
                'verbose_name_plural': '分片上传任务',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源标题')),
                ('file', models.FileField(upload_to=resources.models.user_directory_path, verbose_name='资源文件')),
                ('md5', models.CharField(editable=False, max_length=32, unique=True, verbose_name='文件MD5')),
                ('version', models.CharField(default='V1.0', max_length=20, verbose_name='版本号')),
                ('school', models.CharField(max_length=100, verbose_name='上传学校')),
                ('subject', models.CharField(max_length=50, verbose_name='学科')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('recall_pending', '召回待审核')], default='pending', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
