# Generated by Django 4.2.26 on 2025-11-28 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载量'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_high_quality',
            field=models.BooleanField(default=False, verbose_name='是否优质资源'),
        ),
        migrations.AddField(
            model_name='resource',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='resource',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='previews/', verbose_name='预览文件（PDF/图片）'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('ppt', 'PPT'), ('word', 'Word'), ('pdf', 'PDF'), ('other', '其他')], default='other', max_length=20, verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='resource',
            name='status_tag',
            field=models.CharField(choices=[('normal', '正常'), ('to_fix', '待修正'), ('removed', '已下架')], default='normal', max_length=20, verbose_name='资源状态标签'),
        ),
        migrations.AddField(
            model_name='resource',
            name='usage_scenario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使用场景'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('content_error', '内容错误'), ('format_error', '格式错误'), ('other', '其他问题')], max_length=20, verbose_name='反馈类型')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='resources.resource', verbose_name='关联资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource', verbose_name='关联资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
